### ISSUE TITLE
NumLock is toggled regardless of existing state

### ISSUE THREAD

**Issue by andrewgdotcom** [keyboardio/Kaleidoscope-Numlock#13]
If my computer is in a state where NumLock is already active for whatever reason, the keyboardio Num key blindly toggles NumLock without testing if it is already active.

Solution: test the NumLock LED state to determine whether a toggle is necessary, and return the NumLock state to whatever it was previously, rather than to off.

**Comment by andrewgdotcom** [comment]
Just realised this is already in #12 ...

**Comment by algernon** [comment]
This should be fixed with the recent merge of #12.

**Comment by andrewgdotcom** [comment]
I don't think this is fixed... I'm not 100% sure I've updated the submodules properly, but I'm still seeing the same behaviour.

**Comment by algernon** [comment]
Do you have a second keyboard? If so, can you try turning NumLock on using that? Does the Model01 switch to NumPad mode too? If it doesn't then either I screwed up the fix, or you haven't updated everything.

I'll give it a try later today using master of eveything, to make sure we're on the same page.

**Comment by andrewgdotcom** [comment]
Yes, I have my old keyboard plugged in as well as the model01 - that's how I noticed the issue in the first place. I can toggle numlock with the old keyboard and the model01 does not respond. When I use numlock on the model01, it toggles numlock (as seen on the old keyboard) to whatever the inverse state is.

**Comment by andrewgdotcom** [comment]
I haven't ruled out the possibility that I haven't updated the firmware properly. I did follow the instructions to update the modules and then make flash - and the leds on the model01 now stop on the letter D where they stopped on E before, so something has definitely changed in the firmware (image size?).

**Comment by bjanders** [comment]
I think the change has not yet been fully merged into to project when you do a recursive pull. It checks out an older version:
`Submodule path 'libraries/Kaleidoscope-Numlock': checked out '393bba00ba7c21764b786ffd9e8f8b3b21ce9e9b'`
When I manually checked out the head, it breaks the build due to missing definition of `kaleidoscope::hid::getKeyboardLEDs()` which is probably the reason head is not checked out.

**Comment by algernon** [comment]
...and indeed, keyboardio/Kaleidoscope#224 is still open. That will need to be merged, and submodules brought up to date.

(/cc @obra)

**Comment by obra** [comment]
Ack. So sorry I missed that.

**Comment by bjanders** [comment]
I just did pull of the latest code, and now the numpad reacts to the state reported by the OS. Nice! Thanks for the fix!

**Comment by andrewgdotcom** [comment]
Works for me too!

**Comment by andrewgdotcom** [comment]
Sigh.

So now the numpad doesn't work on Mac, because Mac doesn't *have* a numlock indicator.

**Comment by algernon** [comment]
Oh, how lovely. I think I have an idea about that, too. Will see if I can get there this weekend.

**Comment by andrewgdotcom** [comment]
Can we not make it that Num coerces the OS NumLock if it has to, and just leave it at that? Do we ever want to disable NumLock?

**Comment by andrewgdotcom** [comment]
I replaced Key_NumpadNumLock with LockLayer(NUMLOCK) in my keymaps and it behaves a lot more like how I would naively expect. 

However, the new behaviour of the NumLock plugin resets the state of the numpad layer to match the OS numlock state on startup (i.e. connection). This means that if I connect to a PC that has NumLock-on-boot NumLock gets immediately enabled. This is counterintuitive.

**Comment by algernon** [comment]
As this module has been replaced with [Kaleidoscope-NumPad](https://github.com/keyboardio/Kaleidoscope-NumPad), I'm tempted to close it here. If it still happens with `NumPad`, can you open an issue there?

Thanks!
