### ISSUE TITLE
After toggling numlock off, some LED modes don't restore the original colors

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope-Numlock#7]
The issue is that in some modes the keys which were lit up red don't go back to their original colors when exiting numpad mode.
Reported by Eric Tang

I suspect this is related to our led state caching.

**Comment by algernon** [comment]
This is my fault, will fix it in a bit. TL;DR is that key caching starts with an empty state, so when numlock turns on, the rest of the key cache is still empty, or out of date.

We need a full update of the cache both at keyboard boot, and when changing layers.

I'll send a PR against `Kaleidoscope` in a bit.
